// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/skdiver33/gophermart/internal/withdraw (interfaces: WithdrawStorageInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	withdraw "github.com/skdiver33/gophermart/internal/withdraw"
)

// MockWithdrawStorageInterface is a mock of WithdrawStorageInterface interface.
type MockWithdrawStorageInterface struct {
	ctrl     *gomock.Controller
	recorder *MockWithdrawStorageInterfaceMockRecorder
}

// MockWithdrawStorageInterfaceMockRecorder is the mock recorder for MockWithdrawStorageInterface.
type MockWithdrawStorageInterfaceMockRecorder struct {
	mock *MockWithdrawStorageInterface
}

// NewMockWithdrawStorageInterface creates a new mock instance.
func NewMockWithdrawStorageInterface(ctrl *gomock.Controller) *MockWithdrawStorageInterface {
	mock := &MockWithdrawStorageInterface{ctrl: ctrl}
	mock.recorder = &MockWithdrawStorageInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWithdrawStorageInterface) EXPECT() *MockWithdrawStorageInterfaceMockRecorder {
	return m.recorder
}

// AddWithdraw mocks base method.
func (m *MockWithdrawStorageInterface) AddWithdraw(arg0 context.Context, arg1 *withdraw.Withdraw) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddWithdraw", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddWithdraw indicates an expected call of AddWithdraw.
func (mr *MockWithdrawStorageInterfaceMockRecorder) AddWithdraw(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWithdraw", reflect.TypeOf((*MockWithdrawStorageInterface)(nil).AddWithdraw), arg0, arg1)
}

// GetAllWithdrawsForUser mocks base method.
func (m *MockWithdrawStorageInterface) GetAllWithdrawsForUser(arg0 context.Context, arg1 int) ([]withdraw.Withdraw, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllWithdrawsForUser", arg0, arg1)
	ret0, _ := ret[0].([]withdraw.Withdraw)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllWithdrawsForUser indicates an expected call of GetAllWithdrawsForUser.
func (mr *MockWithdrawStorageInterfaceMockRecorder) GetAllWithdrawsForUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllWithdrawsForUser", reflect.TypeOf((*MockWithdrawStorageInterface)(nil).GetAllWithdrawsForUser), arg0, arg1)
}

// GetWithdraw mocks base method.
func (m *MockWithdrawStorageInterface) GetWithdraw(arg0 context.Context, arg1 string) (*withdraw.Withdraw, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdraw", arg0, arg1)
	ret0, _ := ret[0].(*withdraw.Withdraw)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdraw indicates an expected call of GetWithdraw.
func (mr *MockWithdrawStorageInterfaceMockRecorder) GetWithdraw(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdraw", reflect.TypeOf((*MockWithdrawStorageInterface)(nil).GetWithdraw), arg0, arg1)
}
