// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/skdiver33/gophermart/internal/order (interfaces: OrderStorageInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	order "github.com/skdiver33/gophermart/internal/order"
)

// MockOrderStorageInterface is a mock of OrderStorageInterface interface.
type MockOrderStorageInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOrderStorageInterfaceMockRecorder
}

// MockOrderStorageInterfaceMockRecorder is the mock recorder for MockOrderStorageInterface.
type MockOrderStorageInterfaceMockRecorder struct {
	mock *MockOrderStorageInterface
}

// NewMockOrderStorageInterface creates a new mock instance.
func NewMockOrderStorageInterface(ctrl *gomock.Controller) *MockOrderStorageInterface {
	mock := &MockOrderStorageInterface{ctrl: ctrl}
	mock.recorder = &MockOrderStorageInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderStorageInterface) EXPECT() *MockOrderStorageInterfaceMockRecorder {
	return m.recorder
}

// AddOrder mocks base method.
func (m *MockOrderStorageInterface) AddOrder(arg0 context.Context, arg1 *order.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOrder", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddOrder indicates an expected call of AddOrder.
func (mr *MockOrderStorageInterfaceMockRecorder) AddOrder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOrder", reflect.TypeOf((*MockOrderStorageInterface)(nil).AddOrder), arg0, arg1)
}

// GetAllOrderForID mocks base method.
func (m *MockOrderStorageInterface) GetAllOrderForID(arg0 context.Context, arg1 int) ([]order.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllOrderForID", arg0, arg1)
	ret0, _ := ret[0].([]order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllOrderForID indicates an expected call of GetAllOrderForID.
func (mr *MockOrderStorageInterfaceMockRecorder) GetAllOrderForID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllOrderForID", reflect.TypeOf((*MockOrderStorageInterface)(nil).GetAllOrderForID), arg0, arg1)
}

// GetOrder mocks base method.
func (m *MockOrderStorageInterface) GetOrder(arg0 context.Context, arg1 string) (*order.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrder", arg0, arg1)
	ret0, _ := ret[0].(*order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockOrderStorageInterfaceMockRecorder) GetOrder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockOrderStorageInterface)(nil).GetOrder), arg0, arg1)
}

// GetUnprocOrders mocks base method.
func (m *MockOrderStorageInterface) GetUnprocOrders(arg0 context.Context) ([]order.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnprocOrders", arg0)
	ret0, _ := ret[0].([]order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnprocOrders indicates an expected call of GetUnprocOrders.
func (mr *MockOrderStorageInterfaceMockRecorder) GetUnprocOrders(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnprocOrders", reflect.TypeOf((*MockOrderStorageInterface)(nil).GetUnprocOrders), arg0)
}

// UpdateOrderStatus mocks base method.
func (m *MockOrderStorageInterface) UpdateOrderStatus(arg0 context.Context, arg1, arg2 string, arg3 float32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatus", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderStatus indicates an expected call of UpdateOrderStatus.
func (mr *MockOrderStorageInterfaceMockRecorder) UpdateOrderStatus(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockOrderStorageInterface)(nil).UpdateOrderStatus), arg0, arg1, arg2, arg3)
}
