// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/skdiver33/gophermart/internal/balance (interfaces: BalanceStorageInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	balance "github.com/skdiver33/gophermart/internal/balance"
)

// MockBalanceStorageInterface is a mock of BalanceStorageInterface interface.
type MockBalanceStorageInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceStorageInterfaceMockRecorder
}

// MockBalanceStorageInterfaceMockRecorder is the mock recorder for MockBalanceStorageInterface.
type MockBalanceStorageInterfaceMockRecorder struct {
	mock *MockBalanceStorageInterface
}

// NewMockBalanceStorageInterface creates a new mock instance.
func NewMockBalanceStorageInterface(ctrl *gomock.Controller) *MockBalanceStorageInterface {
	mock := &MockBalanceStorageInterface{ctrl: ctrl}
	mock.recorder = &MockBalanceStorageInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceStorageInterface) EXPECT() *MockBalanceStorageInterfaceMockRecorder {
	return m.recorder
}

// ChangeBalanceAddAccrual mocks base method.
func (m *MockBalanceStorageInterface) ChangeBalanceAddAccrual(arg0 context.Context, arg1 int, arg2 float32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeBalanceAddAccrual", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeBalanceAddAccrual indicates an expected call of ChangeBalanceAddAccrual.
func (mr *MockBalanceStorageInterfaceMockRecorder) ChangeBalanceAddAccrual(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeBalanceAddAccrual", reflect.TypeOf((*MockBalanceStorageInterface)(nil).ChangeBalanceAddAccrual), arg0, arg1, arg2)
}

// ChangeBalanceAddWithdraw mocks base method.
func (m *MockBalanceStorageInterface) ChangeBalanceAddWithdraw(arg0 context.Context, arg1 int, arg2 float32, arg3 string, arg4 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeBalanceAddWithdraw", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeBalanceAddWithdraw indicates an expected call of ChangeBalanceAddWithdraw.
func (mr *MockBalanceStorageInterfaceMockRecorder) ChangeBalanceAddWithdraw(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeBalanceAddWithdraw", reflect.TypeOf((*MockBalanceStorageInterface)(nil).ChangeBalanceAddWithdraw), arg0, arg1, arg2, arg3, arg4)
}

// CreateUserBalance mocks base method.
func (m *MockBalanceStorageInterface) CreateUserBalance(arg0 context.Context, arg1 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserBalance", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUserBalance indicates an expected call of CreateUserBalance.
func (mr *MockBalanceStorageInterfaceMockRecorder) CreateUserBalance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserBalance", reflect.TypeOf((*MockBalanceStorageInterface)(nil).CreateUserBalance), arg0, arg1)
}

// GetUserBalance mocks base method.
func (m *MockBalanceStorageInterface) GetUserBalance(arg0 context.Context, arg1 int) (*balance.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserBalance", arg0, arg1)
	ret0, _ := ret[0].(*balance.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserBalance indicates an expected call of GetUserBalance.
func (mr *MockBalanceStorageInterfaceMockRecorder) GetUserBalance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserBalance", reflect.TypeOf((*MockBalanceStorageInterface)(nil).GetUserBalance), arg0, arg1)
}
